In [1]:
from sympy import *
import numpy

In [2]:
a1, a2 = symbols('a1, a2')

MSE = 1 / 4 * ((4.1 * a1 + 3.9 * a2 - 4.0)**2 + \
               (4.7 * a1 + 4.2 * a2 - 4.3)**2 + \
               (3.1 * a1 + 2.9 * a2 - 3.0)**2 + \
               (4.9 * a1 + 5.0 * a2 - 4.9)**2)
MSE.subs({a1: 0, a2: 0})

16.8750000000000

In [3]:
MSEa1 = diff(MSE, a1)
MSEa1

36.26*a1 + 34.61*a2 - 34.96

In [4]:
MSEa2 = diff(MSE, a2)
MSEa2

34.61*a1 + 33.13*a2 - 33.43

In [5]:
step = 0.01

In [6]:
point = numpy.array([0, 0])

In [7]:
grad = numpy.array([MSEa1.subs({a1: point[0], a2: point[1]}),
                    MSEa2.subs({a1: point[0], a2: point[1]})])
grad

array([-34.9600000000000, -33.4300000000000], dtype=object)

In [8]:
next_point = point - step * grad
next_point

array([0.349600000000000, 0.334300000000000], dtype=object)

In [9]:
MSE.subs({a1: next_point[0], a2: next_point[1]})

1.58934775845000

# Практическая работа

In [17]:
from sympy import *
import numpy
x,y,z = symbols("x,y,z")

In [11]:
X = Matrix([[-1,7,-34], [8,8,-48]])
linsolve(X, [x,y])

{(-1, -5)}

In [14]:
A = Matrix([[-1, 7],[8,8]])
A

Matrix([
[-1, 7],
[ 8, 8]])

In [15]:
b = Matrix([-1,-5])
b

Matrix([
[-1],
[-5]])

In [16]:
A * b

Matrix([
[-34],
[-48]])

In [20]:
eq1 = 5*x + 7*y - 5*z + 47
eq2 = -2*y + 2*z - 10
eq3 = -4*x - 8*y - 7*z - 63
eq4 = x + y + 2*z + 1
eq5 = 2*x - y + 2*z + 4
eq6 = 4*x + y + 4*z + 2

In [21]:
MSE = 1/6 * (eq1**2 + eq2**2 + eq3**2 + eq4**2 + eq5**2 + eq6**2)
MSE

0.166666666666667*(-2*y + 2*z - 10)**2 + 0.166666666666667*(-4*x - 8*y - 7*z - 63)**2 + 0.166666666666667*(x + y + 2*z + 1)**2 + 0.166666666666667*(2*x - y + 2*z + 4)**2 + 0.166666666666667*(4*x + y + 4*z + 2)**2 + 0.166666666666667*(5*x + 7*y - 5*z + 47)**2

In [23]:
MSEx = diff(MSE, x)
MSEx

20.6666666666667*x + 23.3333333333333*y + 8.33333333333333*z + 168.0

In [24]:
MSEy = diff(MSE, y)
MSEy

23.3333333333333*x + 40.0*y + 6.99999999999999*z + 284.0

In [25]:
MSEz = diff(MSE, z)
MSEz

8.33333333333333*x + 6.99999999999999*y + 34.0*z + 68.0

In [28]:
point = numpy.array([0,0,0])
step = 0.01

In [43]:
grad = numpy.array([MSEx.subs({x: point[0], y: point[1], z: point[2]}),
                    MSEy.subs({x: point[0], y: point[1], z: point[2]}),
                    MSEz.subs({x: point[0], y: point[1], z: point[2]})])
print(grad)
next_point = point - step * grad
print(next_point)
print(MSE.subs({x: next_point[0], y: next_point[1], z : next_point[2]}))
point = next_point

[-9.41361525358937 7.21990210686288 -1.00539271063512]
[-1.94928823396929 -5.73624833862081 -0.352549335645414]
49.5397376262838


In [46]:
print(eq1.subs({x: next_point[0], y: next_point[1], z : next_point[2]}))

-1.13743286196504
