## Свойства коэффициентов кубической функции. Практика

В качестве практики подберите, как и в прошлый раз, варьируя коэффициенты, функцию для набора точек. Только в этот раз функция будет кубическая. Получается, вам нужно решить задачу интерполяции полиномом третьей степени. Интерфейс для выполнения задания аналогичен тому, который был в практике к предыдущему уроку.

In [1]:
%matplotlib inline
from ipywidgets import interactive
import matplotlib.pyplot as plt
import numpy as np

In [1]:
def get_polyfunc_title(koefs):
    s_koefs = ''.join([f'+{koefs[i]}x^{len(koefs)-i-1}' if koefs[i]>0
                       else f'{koefs[i]}x^{len(koefs)-i-1}' if koefs[i]<0
                       else ''
                       for i in range(len(koefs))])
    expr = s_koefs.replace('x^0', '') \
                  .replace('+', ' + ') \
                  .replace('-', ' - ') \
                  .replace('x^1', 'x') \
                  .replace(' 1x', ' x')

    if expr[:3]==' + ':
        expr = expr[3:]
    if expr:
        return '$f(x) = ' + expr + '$'

def check(f, x, y):
    check = False not in [f(x[i])==y[i] for i in range(len(x))]
    if not check:
        print('Пока не получилось')
    else:
        print('Ура! Получилось!')

In [2]:
def cubic_parabola(a, b, c, d):
    plt.figure(3)
    plt.axhline(0, color='black')
    plt.axvline(0, color='black')

    x, y = [x for x, y in points], [y for x, y in points]
    plt.scatter(x, y, c='r')

    if a!=0:
        f = lambda x: a * x**3 + b * x**2 + c * x + d
        check(f, x, y)

        x = np.linspace(-15, 15, num=1000)
        plt.plot(x, a * x**3 + b * x**2 + c * x + d)

    plt.ylim(-35, 35)
    plt.xlim(-5, 5)

    plt.title(get_polyfunc_title([a,b,c,d]))

    plt.show()

In [5]:
points = [[-0.5, -15.0],
          [-1, -31],
          [0, -7],
          [0.5, -4.0],
          [1, -3],
          [2, 5],
          [2.5, 18.0],
          [3, 41]]

interactive_plot = interactive(cubic_parabola, a=(-15, 15, 1), b=(-10, 10, 1), c=(-10, 10, 1), d=(-10, 10, 1))
output = interactive_plot.children[-1]
output.layout.height = '300px'
interactive_plot

interactive(children=(IntSlider(value=0, description='a', max=15, min=-15), IntSlider(value=0, description='b'…

In [ ]:
points = [[-5.0, -68.0],
          [-3.75, -8.234375],
          [-2.5, 16.375],
          [-1.25, 17.546875],
          [0.0, 7.0],
          [1.25, -3.546875],
          [2.5, -2.375],
          [3.75, 22.234375],
          [5.0, 82.0]]

interactive_plot = interactive(cubic_parabola, a=(-15, 15, 1), b=(-10, 10, 1), c=(-10, 10, 1), d=(-10, 10, 1))
output = interactive_plot.children[-1]
output.layout.height = '300px'
interactive_plot

interactive(children=(IntSlider(value=0, description='a', max=15, min=-15), IntSlider(value=0, description='b'…

Есть два одинаковых по массе куска чугуна с разным содержанием хрома. Процентное содержание хрома в первом куске на 5 меньше, чем во втором. Сплавив эти куски, получили сплав, в котором содержится 12 кг хрома. Если бы масса первого куска была в 2 раза больше, то в сплаве содержалось бы 16 кг хрома. 

Задание: найдите процентное содержание хрома в каждом куске чугуна.

In [1]:
from sympy import*
from sympy.solvers.solveset import linsolve
init_printing(use_unicode = False, wrap_line = False, no_global=True)
from sympy.solvers.inequalities import solve_univariate_inequality

In [3]:
b

Значит хрома в кусках было 4 и 8 кr
Остается найти такую массу, где "Процентное содержание хрома в первом куске на 5 меньше" дает 4 и 8

In [70]:
eq3 = 4/m1 - 8/m2 + 0.05 # Процентное содержание хрома в первом куске на 5 меньше
eq4 = m1-m2              # массы двух кусков равны
nonlinsolve([eq3,eq4], [m1, m2])

Нулевые решения не подходят, значит масса кусков была по 80kg
Остается арифметически посчитать процентное содержание хрома в кусках

In [48]:
perc1 = 4 / 80
perc2 = 8 / 80
print("Процентное содержание хрома в каждом куске чугуна")
print("В первом куске:", perc1)
print("Во втором куске:", perc2)

Процентное содержание хрома в каждом куске чугуна
В первом куске: 0.05
Во втором куске: 0.1


In [5]:
from sympy import*
from sympy.solvers.solveset import linsolve
init_printing(use_unicode = False, wrap_line = False, no_global=True)
from sympy.solvers.inequalities import solve_univariate_inequality

In [6]:
xv = [200, 300, 600]
yv = [2, 1, 3]
sv = [200, 450, 550]

In [8]:
x1,x2,x3 = symbols("x1,x2,x3")
a0,a1,a2,a3 = symbols("a0,a1,a2,a3")

In [11]:
f = a2 * x2 + a1 * x1 + a0

In [22]:
MSE1 = ((200 * a2 + 2 * a1 + a0 - 200)**2) / 3
MSE2 = ((300 * a2 + 1 * a1 + a0 - 450)**2) / 3
MSE3 = ((600 * a2 + 3 * a1 + a0 - 550)**2) / 3
MSE = MSE1 + MSE2 + MSE3
print(MSE)

(a0 + a1 + 300*a2 - 450)**2/3 + (a0 + 2*a1 + 200*a2 - 200)**2/3 + (a0 + 3*a1 + 600*a2 - 550)**2/3


In [23]:
MSEa2 = MSE.diff(a2)
MSEa1 = MSE.diff(a1)
MSEa0 = MSE.diff(a0)
print(MSEa2)
print(MSEa1)
print(MSEa0)

2200*a0/3 + 5000*a1/3 + 980000*a2/3 - 1010000/3
4*a0 + 28*a1/3 + 5000*a2/3 - 5000/3
2*a0 + 4*a1 + 2200*a2/3 - 800


In [24]:
nonlinsolve([MSEa2,MSEa1,MSEa0], [a2,a1,a0])

In [25]:
f = 6/5 * x1 - 130 * x2 + 220

In [27]:
f.subs({x1:666, x2:4})

1945 кг 560 л. с. 4,3 с
1495 кг 340 л. с. 4,9 с
1570 кг 343 л. с. 5,2 с
1520 кг 431 л. с. ? с

In [28]:
MSE1 = ((1945 * a2 + 560 * a1 + a0 - 4.3)**2)
MSE2 = ((1495 * a2 + 340 * a1 + a0 - 4.9)**2)
MSE3 = ((1570 * a2 + 343 * a1 + a0 - 5.2)**2)
MSE = (MSE1 + MSE2 + MSE3) / 3
print(MSE)

3783025*(a0/1945 + 112*a1/389 + a2 - 0.00221079691516709)**2/3 + 2464900*(a0/1570 + 343*a1/1570 + a2 - 0.00331210191082803)**2/3 + 2235025*(a0/1495 + 68*a1/299 + a2 - 0.00327759197324415)**2/3


In [29]:
MSEa2 = MSE.diff(a2)
MSEa1 = MSE.diff(a1)
MSEa0 = MSE.diff(a0)
print(MSEa2)
print(MSEa1)
print(MSEa0)

3340*a0 + 4272020*a1/3 + 5655300*a2 - 15902.0
2486*a0/3 + 364566*a1 + 4272020*a2/3 - 3905.06666666667
2*a0 + 2486*a1/3 + 3340*a2 - 9.6


In [40]:
solution = list(nonlinsolve([MSEa2,MSEa1,MSEa0], [a2,a1,a0]))
solution

In [42]:
f = solution[0][0] * x1 + solution[0][1] * x2 + solution[0][2]
f.subs({x1:1520, x2:431})

# Матрицы и вектора

In [2]:
a = np.array([2, 5, 0, 6, 8, 10, 6, 7, 5, 7])
b = np.array([8, 6, 7, 9, 6, 6, 2, 3, 2, 3])
(3*a) @ (2*b)

1632

In [3]:
v1 = np.array([1,1,1])
v2 = np.array([2,2,2])
3*v1

array([3, 3, 3])

In [4]:
v1 @ v2

6

In [6]:
def transpose(matrix: np.array) -> np.array:
    transposed_matrix = np.ndarray(shape=matrix.shape[::-1], dtype=matrix.dtype)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            transposed_matrix[j, i] = matrix[i, j]
    return transposed_matrix

In [8]:
A = np.array(
[[2, 1, 7, 4], 
[5, 6, 7, 3], 
[9, 8, 2, 12], 
[11, 14, 15, 15]], dtype=np.int32
)
A

array([[ 2,  1,  7,  4],
       [ 5,  6,  7,  3],
       [ 9,  8,  2, 12],
       [11, 14, 15, 15]])

In [10]:
transpose(A)

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

In [11]:
A.T

array([[ 2,  5,  9, 11],
       [ 1,  6,  8, 14],
       [ 7,  7,  2, 15],
       [ 4,  3, 12, 15]])

В лесу 99% деревьев составляют сосны. Леспромхоз решил вырубить сосны так, чтобы доля уменьшилась до 98%.
Какую часть леса нужно вырубить?

In [5]:
from sympy import*
from sympy.solvers.solveset import linsolve

In [2]:
s,f,v = symbols("s,f,v")

s = 0.99*f               # сосны составляют 99% леса
s-v = 0.98 * (f - v)     # сосны минус вырубка составят 98% леса минус вырубка

In [3]:
eq1 = 0.99 * f - s             
eq2 = 0.98 * (f - v) - (s - v)
nonlinsolve([eq1,eq2], [s,v,f])

{(1.98*v, v, 2.0*v)}

То есть лес должен быть в два раза бльше вырубки
Ответ - придется вырубить 50% леса

In [13]:
from sympy import*
X = Matrix([[4.1, 3.9, 4.0], [4.7, 4.2, 4.3]])
X

Matrix([
[4.1, 3.9, 4.0],
[4.7, 4.2, 4.3]])

In [14]:
a1,a2 = symbols("a1,a2")
linsolve(X, [a1,a2])

{(-0.0270270270270284, 1.05405405405406)}